import { Black_Ops_One } from 'next/font/google'
import './globals.css'

const rubik = Black_Ops_One({weight: ['400'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
