import "./globals.css";
import Menu from "./components/header";
import { audiowave } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth">
      <body className={`${audiowave.className}`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
